import React, { useState, useEffect, useRef } from "react";
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  AreaChart,
  Area,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
} from "recharts";
import {
  Clock,
  Zap,
  Target,
  TrendingUp,
  Download,
  Eye,
  FileText,
  Award,
  Keyboard,
  Trophy,
  Flame,
  Star,
  Activity,
  BarChart3,
  Settings,
} from "lucide-react";

const TypingProductivityAnalyzer = () => {
  const [currentView, setCurrentView] = useState("typing");
  const [typingText, setTypingText] = useState("");
  const [aiParagraph, setAiParagraph] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [displayedText, setDisplayedText] = useState("");
  const [typingSpeed, setTypingSpeed] = useState(0);
  const [accuracy, setAccuracy] = useState(100);
  const [startTime, setStartTime] = useState(null);
  const [errors, setErrors] = useState(0);
  const [sessions, setSessions] = useState([]);
  const [currentSession, setCurrentSession] = useState(null);
  const [difficulty, setDifficulty] = useState("medium");
  const [streak, setStreak] = useState(0);
  const [totalWords, setTotalWords] = useState(0);
  const [mostProblematicKeys, setMostProblematicKeys] = useState([]);
  const typingIndex = useRef(0);
  const intervalRef = useRef(null);
  const keystrokeData = useRef({});
  const hasAutoGenerated = useRef(false);

  // Difficulty settings
  const difficultySettings = {
    easy: {
      label: "Easy",
      prompt:
        "Generate a simple paragraph (80-100 words) using common, everyday words. Keep sentences short and straightforward. Suitable for beginners.",
      color: "green",
      minWPM: 20,
    },
    medium: {
      label: "Medium",
      prompt:
        "Generate an interesting paragraph (100-120 words) about productivity, technology, or innovation. Use moderate vocabulary and varied sentence structure.",
      color: "blue",
      minWPM: 40,
    },
    hard: {
      label: "Hard",
      prompt:
        "Generate a complex, sophisticated paragraph (120-150 words) with advanced vocabulary, technical terms, and intricate sentence structures. Include punctuation variety.",
      color: "red",
      minWPM: 60,
    },
    expert: {
      label: "Expert",
      prompt:
        "Generate an extremely challenging paragraph (150-180 words) with specialized terminology, complex syntax, extensive punctuation (semicolons, em-dashes, parentheses), and advanced concepts.",
      color: "purple",
      minWPM: 80,
    },
  };

  // Calculate streak
  const calculateStreak = (sessionList) => {
    if (sessionList.length === 0) return;

    let currentStreak = 0;
    const today = new Date().setHours(0, 0, 0, 0);

    for (let i = 0; i < sessionList.length; i++) {
      const sessionDate = new Date(sessionList[i].timestamp).setHours(
        0,
        0,
        0,
        0
      );
      const daysDiff = Math.floor(
        (today - sessionDate) / (1000 * 60 * 60 * 24)
      );

      if (daysDiff === currentStreak) {
        currentStreak++;
      } else {
        break;
      }
    }

    setStreak(currentStreak);
  };

  // Load sessions from storage
  useEffect(() => {
    const loadSessions = async () => {
      try {
        const result = await window.storage.list("session:");
        if (result && result.keys) {
          const sessionPromises = result.keys.map((key) =>
            window.storage.get(key).catch(() => null)
          );
          const sessionResults = await Promise.all(sessionPromises);
          const loadedSessions = sessionResults
            .filter((r) => r && r.value)
            .map((r) => {
              try {
                return JSON.parse(r.value);
              } catch {
                return null;
              }
            })
            .filter((s) => s !== null)
            .sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
          setSessions(loadedSessions);

          calculateStreak(loadedSessions);

          const words = loadedSessions.reduce((sum, s) => {
            const text = s.typedText || "";
            return (
              sum +
              text
                .trim()
                .split(/\s+/)
                .filter((w) => w.length > 0).length
            );
          }, 0);
          setTotalWords(words);
        }
      } catch (error) {
        console.log("No previous sessions found");
      }
    };
    loadSessions();

    // Auto-generate paragraph on load (only once)
    if (!hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateAIParagraph();
    }
  }, []);

  // Generate AI paragraph using Claude API
  const generateAIParagraph = async () => {
    setIsGenerating(true);
    const currentDifficulty = difficultySettings[difficulty];

    const fallbackParagraphs = {
      easy: "The sun was bright today. I went to the park with my friend. We played games and had fun. The day was very nice. We ate lunch under a big tree. It was a good time. Everyone enjoyed the beautiful weather.",
      medium:
        "The future of work is being reshaped by artificial intelligence and automation. As machines take over repetitive tasks, humans are freed to focus on creative problem-solving and strategic thinking. This shift requires continuous learning and adaptation, but it also opens up unprecedented opportunities for innovation and personal growth in the digital age.",
      hard: "Quantum computing represents a paradigm shift in computational capability, leveraging superposition and entanglement to process information exponentially faster than classical computers. This revolutionary technology potentially transforms cryptography, drug discovery, and complex system optimization, presenting both remarkable opportunities and significant challenges for researchers worldwide.",
      expert:
        "The epistemological implications of machine learning algorithms—particularly their capacity for pattern recognition beyond human cognitive thresholds—necessitate fundamental reassessment of our ontological frameworks; moreover, the recursive self-improvement potential (colloquially termed 'intelligence explosion') presents unprecedented existential considerations that transcend traditional risk-assessment methodologies.",
    };

    try {
      const response = await fetch("https://api.openai.com/v1/responses", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${import.meta.env.VITE_OPENAI_API_KEY}`,
        },
        body: JSON.stringify({
          model: "gpt-5.1",
          input: currentDifficulty.prompt,
        }),
      });

      const data = await response.json();
      if (data.content && data.content[0] && data.content[0].text) {
        const paragraph = data.content[0].text.trim();
        setAiParagraph(paragraph);
        setDisplayedText("");
        typingIndex.current = 0;
        startTypingEffect(paragraph);
      } else {
        throw new Error("Invalid API response");
      }
    } catch (error) {
      console.log("Using fallback paragraph");
      const paragraph = fallbackParagraphs[difficulty];
      setAiParagraph(paragraph);
      setDisplayedText("");
      typingIndex.current = 0;
      startTypingEffect(paragraph);
    }
    setIsGenerating(false);
  };

  // Typing effect animation
  const startTypingEffect = (text) => {
    if (intervalRef.current) clearInterval(intervalRef.current);

    intervalRef.current = setInterval(() => {
      if (typingIndex.current < text.length) {
        setDisplayedText(text.slice(0, typingIndex.current + 1));
        typingIndex.current++;
      } else {
        clearInterval(intervalRef.current);
      }
    }, 30);
  };

  useEffect(() => {
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, []);

  // Update problematic keys
  const updateProblematicKeys = () => {
    const keyArray = Object.entries(keystrokeData.current)
      .map(([key, count]) => ({ key, errors: count }))
      .sort((a, b) => b.errors - a.errors)
      .slice(0, 5);
    setMostProblematicKeys(keyArray);
  };

  // Handle typing input
  const handleTypingChange = (e) => {
    const value = e.target.value;
    setTypingText(value);

    if (!startTime) {
      setStartTime(Date.now());
      setCurrentSession({
        id: `session:${Date.now()}`,
        timestamp: new Date().toISOString(),
        targetText: aiParagraph,
        typedText: value,
        duration: 0,
        wpm: 0,
        accuracy: 100,
        errors: 0,
        difficulty: difficulty,
        keystrokes: {},
      });
    }

    const timeElapsed = (Date.now() - (startTime || Date.now())) / 1000 / 60;
    const wordsTyped = value
      .trim()
      .split(/\s+/)
      .filter((w) => w.length > 0).length;
    const wpm = timeElapsed > 0 ? Math.round(wordsTyped / timeElapsed) : 0;
    setTypingSpeed(wpm);

    let errorCount = 0;
    for (let i = 0; i < value.length; i++) {
      if (value[i] !== aiParagraph[i]) {
        errorCount++;
        const expectedKey = aiParagraph[i];
        if (expectedKey) {
          keystrokeData.current[expectedKey] =
            (keystrokeData.current[expectedKey] || 0) + 1;
        }
      }
    }
    setErrors(errorCount);
    const acc =
      aiParagraph.length > 0
        ? Math.max(0, Math.round((1 - errorCount / aiParagraph.length) * 100))
        : 100;
    setAccuracy(acc);

    updateProblematicKeys();
  };

  // Save session
  const saveSession = async () => {
    if (!currentSession || typingText.length === 0) {
      alert("Please type something before saving!");
      return;
    }

    const timeElapsed = (Date.now() - startTime) / 1000;
    const finalSession = {
      ...currentSession,
      typedText: typingText,
      duration: Math.round(timeElapsed),
      wpm: typingSpeed,
      accuracy: accuracy,
      errors: errors,
      difficulty: difficulty,
      completed: typingText.length >= aiParagraph.length,
      keystrokes: { ...keystrokeData.current },
    };

    try {
      await window.storage.set(finalSession.id, JSON.stringify(finalSession));
      setSessions((prev) => [finalSession, ...prev]);
      setTotalWords(
        (prev) =>
          prev +
          typingText
            .trim()
            .split(/\s+/)
            .filter((w) => w.length > 0).length
      );
      alert("Session saved successfully! 🎉");
      resetTest();
    } catch (error) {
      console.error("Failed to save session:", error);
      alert("Failed to save session. Please try again.");
    }
  };

  // Reset typing test
  const resetTest = () => {
    setTypingText("");
    setStartTime(null);
    setTypingSpeed(0);
    setAccuracy(100);
    setErrors(0);
    setCurrentSession(null);
    keystrokeData.current = {};
    setMostProblematicKeys([]);
    generateAIParagraph();
  };

  // Dashboard statistics
  const calculateStats = () => {
    if (sessions.length === 0) return null;

    const totalSessions = sessions.length;
    const avgWPM = Math.round(
      sessions.reduce((sum, s) => sum + (s.wpm || 0), 0) / totalSessions
    );
    const avgAccuracy = Math.round(
      sessions.reduce((sum, s) => sum + (s.accuracy || 0), 0) / totalSessions
    );
    const totalTime = sessions.reduce((sum, s) => sum + (s.duration || 0), 0);
    const bestWPM = Math.max(...sessions.map((s) => s.wpm || 0));
    const improvementRate =
      sessions.length > 1
        ? Math.round(
            ((sessions[0].wpm - sessions[sessions.length - 1].wpm) /
              (sessions[sessions.length - 1].wpm || 1)) *
              100
          )
        : 0;

    return {
      totalSessions,
      avgWPM,
      avgAccuracy,
      totalTime,
      bestWPM,
      improvementRate,
    };
  };

  const stats = calculateStats();

  // Chart data
  const chartData = sessions
    .slice(0, 15)
    .reverse()
    .map((s, i) => ({
      session: `S${sessions.length - sessions.slice(0, 15).length + i + 1}`,
      WPM: s.wpm || 0,
      Accuracy: s.accuracy || 0,
      Errors: s.errors || 0,
    }));

  // Weekly progress data
  const getWeeklyData = () => {
    const weeks = {};
    sessions.forEach((s) => {
      const date = new Date(s.timestamp);
      const weekStart = new Date(date.setDate(date.getDate() - date.getDay()));
      const weekKey = weekStart.toISOString().split("T")[0];

      if (!weeks[weekKey]) {
        weeks[weekKey] = {
          week: weekKey,
          sessions: 0,
          totalWPM: 0,
          totalAccuracy: 0,
        };
      }
      weeks[weekKey].sessions++;
      weeks[weekKey].totalWPM += s.wpm || 0;
      weeks[weekKey].totalAccuracy += s.accuracy || 0;
    });

    return Object.values(weeks)
      .map((w) => ({
        week: new Date(w.week).toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
        }),
        avgWPM: Math.round(w.totalWPM / w.sessions),
        avgAccuracy: Math.round(w.totalAccuracy / w.sessions),
        sessions: w.sessions,
      }))
      .slice(-8);
  };

  const weeklyData = getWeeklyData();

  // Difficulty distribution
  const difficultyData = [
    {
      name: "Easy",
      value: sessions.filter((s) => s.difficulty === "easy").length,
      color: "#10b981",
    },
    {
      name: "Medium",
      value: sessions.filter((s) => s.difficulty === "medium" || !s.difficulty)
        .length,
      color: "#3b82f6",
    },
    {
      name: "Hard",
      value: sessions.filter((s) => s.difficulty === "hard").length,
      color: "#ef4444",
    },
    {
      name: "Expert",
      value: sessions.filter((s) => s.difficulty === "expert").length,
      color: "#8b5cf6",
    },
  ].filter((d) => d.value > 0);

  const pieData = [
    {
      name: "Completed",
      value: sessions.filter((s) => s.completed).length || 1,
    },
    {
      name: "Incomplete",
      value: sessions.filter((s) => !s.completed).length || 0,
    },
  ];

  const COLORS = ["#10b981", "#f59e0b"];

  // Radar chart data
  const radarData = stats
    ? [
        { skill: "Speed", value: Math.min((stats.avgWPM / 100) * 100, 100) },
        { skill: "Accuracy", value: stats.avgAccuracy },
        {
          skill: "Consistency",
          value: Math.max(100 - (stats.bestWPM - stats.avgWPM), 0),
        },
        {
          skill: "Endurance",
          value: Math.min((stats.totalSessions / 50) * 100, 100),
        },
        {
          skill: "Progress",
          value: Math.max(Math.min(stats.improvementRate + 50, 100), 0),
        },
      ]
    : [];

  const getDifficultyColor = (diff) => {
    const colors = {
      easy: "bg-green-500",
      medium: "bg-blue-500",
      hard: "bg-red-500",
      expert: "bg-purple-500",
    };
    return colors[diff] || colors.medium;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50">
      {/* Navigation */}
      <nav className="bg-white shadow-md">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Zap className="w-8 h-8 text-indigo-600" />
              <h1 className="text-2xl font-bold text-gray-800">TypingPro</h1>
            </div>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 py-8">
        {/* Typing Test View */}
        {currentView === "typing" && (
          <div className="space-y-6">
            {/* Difficulty Selector */}
            <div className="bg-white rounded-xl shadow-lg p-6">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-xl font-bold text-gray-800 flex items-center">
                    <Settings className="w-6 h-6 mr-2 text-indigo-600" />
                    Difficulty Level
                  </h3>
                  <p className="text-sm text-gray-500 mt-1">
                    Choose your challenge level
                  </p>
                </div>
                <div className="flex items-center space-x-2">
                  <Flame className="w-6 h-6 text-orange-500" />
                  <span className="text-2xl font-bold text-orange-600">
                    {streak}
                  </span>
                  <span className="text-sm text-gray-600">day streak</span>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                {Object.entries(difficultySettings).map(([key, setting]) => (
                  <button
                    key={key}
                    onClick={() => {
                      setDifficulty(key);
                      if (!startTime) generateAIParagraph();
                    }}
                    disabled={startTime !== null}
                    className={`p-4 rounded-lg border-2 transition-all ${
                      difficulty === key
                        ? "border-indigo-500 bg-indigo-50"
                        : "border-gray-200 bg-white hover:border-gray-300"
                    } ${
                      startTime
                        ? "opacity-50 cursor-not-allowed"
                        : "cursor-pointer"
                    }`}
                  >
                    <div className="text-center">
                      <div className="text-lg font-bold text-gray-800">
                        {setting.label}
                      </div>
                      <div className="text-xs text-gray-500 mt-1">
                        Target: {setting.minWPM}+ WPM
                      </div>
                      {difficulty === key && (
                        <div className="mt-2">
                          <Star className="w-5 h-5 mx-auto text-indigo-500" />
                        </div>
                      )}
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {/* Real-time Stats */}
            <div className="grid grid-cols-2 md:grid-cols-6 gap-4">
              <div className="bg-white rounded-xl shadow-md p-4 border-l-4 border-indigo-500">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-500 text-xs font-medium">WPM</p>
                    <p className="text-2xl font-bold text-indigo-600">
                      {typingSpeed}
                    </p>
                  </div>
                  <Zap className="w-8 h-8 text-indigo-200" />
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-md p-4 border-l-4 border-green-500">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-500 text-xs font-medium">
                      Accuracy
                    </p>
                    <p className="text-2xl font-bold text-green-600">
                      {accuracy}%
                    </p>
                  </div>
                  <Target className="w-8 h-8 text-green-200" />
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-md p-4 border-l-4 border-red-500">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-500 text-xs font-medium">Errors</p>
                    <p className="text-2xl font-bold text-red-600">{errors}</p>
                  </div>
                  <Eye className="w-8 h-8 text-red-200" />
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-md p-4 border-l-4 border-purple-500">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-500 text-xs font-medium">Time</p>
                    <p className="text-2xl font-bold text-purple-600">
                      {startTime
                        ? Math.round((Date.now() - startTime) / 1000)
                        : 0}
                      s
                    </p>
                  </div>
                  <Clock className="w-8 h-8 text-purple-200" />
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-md p-4 border-l-4 border-orange-500">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-500 text-xs font-medium">
                      Progress
                    </p>
                    <p className="text-2xl font-bold text-orange-600">
                      {aiParagraph
                        ? Math.round(
                            (typingText.length / aiParagraph.length) * 100
                          )
                        : 0}
                      %
                    </p>
                  </div>
                  <Activity className="w-8 h-8 text-orange-200" />
                </div>
              </div>

              <div className="bg-white rounded-xl shadow-md p-4 border-l-4 border-pink-500">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-500 text-xs font-medium">Words</p>
                    <p className="text-2xl font-bold text-pink-600">
                      {totalWords}
                    </p>
                  </div>
                  <FileText className="w-8 h-8 text-pink-200" />
                </div>
              </div>
            </div>

            {/* AI Paragraph Display */}
            <div className="bg-white rounded-xl shadow-lg p-8">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold text-gray-800">
                  AI-Generated Practice Text
                </h2>
                {/* <button
                  onClick={generateAIParagraph}
                  disabled={isGenerating || startTime !== null}
                  className="px-6 py-3 bg-gradient-to-r from-indigo-500 to-purple-600 text-white rounded-lg font-medium hover:from-indigo-600 hover:to-purple-700 transition-all shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isGenerating ? 'Generating...' : 'Generate New Text'}
                </button> */}
              </div>

              <div className="bg-gradient-to-r from-indigo-50 to-purple-50 rounded-lg p-6 mb-6 min-h-[150px]">
                <p className="text-lg text-gray-700 leading-relaxed font-mono">
                  {displayedText || "Generating your practice text..."}
                  {displayedText &&
                    displayedText.length < aiParagraph.length && (
                      <span className="animate-pulse">|</span>
                    )}
                </p>
              </div>

              <textarea
                value={typingText}
                onChange={handleTypingChange}
                placeholder="Start typing here to match the text above..."
                className="w-full h-40 p-4 border-2 border-gray-300 rounded-lg focus:border-indigo-500 focus:outline-none text-lg font-mono resize-none"
                disabled={!aiParagraph}
              />

              <div className="flex space-x-4 mt-4">
                {/* <button
                  onClick={saveSession}
                  disabled={!typingText}
                  className="flex-1 px-6 py-3 bg-green-500 text-white rounded-lg font-medium hover:bg-green-600 transition-all shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Download className="w-5 h-5 inline mr-2" />
                  Save Session
                </button> */}
                <button
                  onClick={resetTest}
                  className="flex-1 px-6 py-3 bg-gray-500 text-white rounded-lg font-medium hover:bg-gray-600 transition-all shadow-md"
                >
                  Reset Test
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Dashboard View */}
        {currentView === "dashboard" && (
          <div className="space-y-6">
            <div className="bg-white rounded-xl shadow-lg p-8">
              <h2 className="text-3xl font-bold text-gray-800 mb-6 flex items-center">
                <Award className="w-8 h-8 mr-3 text-indigo-600" />
                Your Productivity Dashboard
              </h2>

              {stats ? (
                <>
                  {/* Summary Cards */}
                  <div className="grid grid-cols-2 md:grid-cols-6 gap-4 mb-8">
                    <div className="bg-gradient-to-br from-indigo-500 to-indigo-600 rounded-xl shadow-md p-4 text-white">
                      <p className="text-xs opacity-90 mb-1">Total Sessions</p>
                      <p className="text-3xl font-bold">
                        {stats.totalSessions}
                      </p>
                      <Trophy className="w-5 h-5 mt-2 opacity-80" />
                    </div>
                    <div className="bg-gradient-to-br from-green-500 to-green-600 rounded-xl shadow-md p-4 text-white">
                      <p className="text-xs opacity-90 mb-1">Avg WPM</p>
                      <p className="text-3xl font-bold">{stats.avgWPM}</p>
                      <Zap className="w-5 h-5 mt-2 opacity-80" />
                    </div>
                    <div className="bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl shadow-md p-4 text-white">
                      <p className="text-xs opacity-90 mb-1">Avg Accuracy</p>
                      <p className="text-3xl font-bold">{stats.avgAccuracy}%</p>
                      <Target className="w-5 h-5 mt-2 opacity-80" />
                    </div>
                    <div className="bg-gradient-to-br from-orange-500 to-orange-600 rounded-xl shadow-md p-4 text-white">
                      <p className="text-xs opacity-90 mb-1">Best WPM</p>
                      <p className="text-3xl font-bold">{stats.bestWPM}</p>
                      <Award className="w-5 h-5 mt-2 opacity-80" />
                    </div>
                    <div className="bg-gradient-to-br from-pink-500 to-pink-600 rounded-xl shadow-md p-4 text-white">
                      <p className="text-xs opacity-90 mb-1">Total Time</p>
                      <p className="text-3xl font-bold">
                        {Math.round(stats.totalTime / 60)}m
                      </p>
                      <Clock className="w-5 h-5 mt-2 opacity-80" />
                    </div>
                    <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl shadow-md p-4 text-white">
                      <p className="text-xs opacity-90 mb-1">Improvement</p>
                      <p className="text-3xl font-bold">
                        {stats.improvementRate > 0 ? "+" : ""}
                        {stats.improvementRate}%
                      </p>
                      <TrendingUp className="w-5 h-5 mt-2 opacity-80" />
                    </div>
                  </div>

                  {/* Charts */}
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
                    <div className="bg-gray-50 rounded-xl p-6">
                      <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                        <TrendingUp className="w-5 h-5 mr-2 text-indigo-600" />
                        Performance Trend
                      </h3>
                      <ResponsiveContainer width="100%" height={300}>
                        <AreaChart data={chartData}>
                          <CartesianGrid strokeDasharray="3 3" />
                          <XAxis dataKey="session" />
                          <YAxis />
                          <Tooltip />
                          <Legend />
                          <Area
                            type="monotone"
                            dataKey="WPM"
                            stroke="#6366f1"
                            fill="#818cf8"
                            fillOpacity={0.6}
                          />
                          <Area
                            type="monotone"
                            dataKey="Accuracy"
                            stroke="#10b981"
                            fill="#34d399"
                            fillOpacity={0.6}
                          />
                        </AreaChart>
                      </ResponsiveContainer>
                    </div>

                    <div className="bg-gray-50 rounded-xl p-6">
                      <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                        <BarChart3 className="w-5 h-5 mr-2 text-green-600" />
                        Weekly Progress
                      </h3>
                      <ResponsiveContainer width="100%" height={300}>
                        <BarChart data={weeklyData}>
                          <CartesianGrid strokeDasharray="3 3" />
                          <XAxis dataKey="week" />
                          <YAxis />
                          <Tooltip />
                          <Legend />
                          <Bar dataKey="avgWPM" fill="#6366f1" name="Avg WPM" />
                          <Bar
                            dataKey="sessions"
                            fill="#10b981"
                            name="Sessions"
                          />
                        </BarChart>
                      </ResponsiveContainer>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
                    <div className="bg-gray-50 rounded-xl p-6">
                      <h3 className="text-xl font-bold text-gray-800 mb-4">
                        Session Completion
                      </h3>
                      <ResponsiveContainer width="100%" height={250}>
                        <PieChart>
                          <Pie
                            data={pieData}
                            cx="50%"
                            cy="50%"
                            labelLine={false}
                            label={({ name, percent }) =>
                              `${name} ${(percent * 100).toFixed(0)}%`
                            }
                            outerRadius={80}
                            fill="#8884d8"
                            dataKey="value"
                          >
                            {pieData.map((entry, index) => (
                              <Cell
                                key={`cell-${index}`}
                                fill={COLORS[index % COLORS.length]}
                              />
                            ))}
                          </Pie>
                          <Tooltip />
                        </PieChart>
                      </ResponsiveContainer>
                    </div>

                    <div className="bg-gray-50 rounded-xl p-6">
                      <h3 className="text-xl font-bold text-gray-800 mb-4">
                        Difficulty Distribution
                      </h3>
                      <ResponsiveContainer width="100%" height={250}>
                        <PieChart>
                          <Pie
                            data={difficultyData}
                            cx="50%"
                            cy="50%"
                            labelLine={false}
                            label={({ name, value }) => `${name}: ${value}`}
                            outerRadius={80}
                            fill="#8884d8"
                            dataKey="value"
                          >
                            {difficultyData.map((entry, index) => (
                              <Cell key={`cell-${index}`} fill={entry.color} />
                            ))}
                          </Pie>
                          <Tooltip />
                        </PieChart>
                      </ResponsiveContainer>
                    </div>

                    <div className="bg-gray-50 rounded-xl p-6">
                      <h3 className="text-xl font-bold text-gray-800 mb-4">
                        Skill Assessment
                      </h3>
                      <ResponsiveContainer width="100%" height={250}>
                        <RadarChart data={radarData}>
                          <PolarGrid />
                          <PolarAngleAxis dataKey="skill" />
                          <PolarRadiusAxis angle={90} domain={[0, 100]} />
                          <Radar
                            name="Your Skills"
                            dataKey="value"
                            stroke="#6366f1"
                            fill="#6366f1"
                            fillOpacity={0.6}
                          />
                          <Tooltip />
                        </RadarChart>
                      </ResponsiveContainer>
                    </div>
                  </div>

                  {/* Error Analysis Chart */}
                  <div className="bg-gray-50 rounded-xl p-6 mb-8">
                    <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                      <Activity className="w-5 h-5 mr-2 text-red-600" />
                      Error Rate Analysis
                    </h3>
                    <ResponsiveContainer width="100%" height={300}>
                      <LineChart data={chartData}>
                        <CartesianGrid strokeDasharray="3 3" />
                        <XAxis dataKey="session" />
                        <YAxis />
                        <Tooltip />
                        <Legend />
                        <Line
                          type="monotone"
                          dataKey="Errors"
                          stroke="#ef4444"
                          strokeWidth={2}
                        />
                      </LineChart>
                    </ResponsiveContainer>
                  </div>
                </>
              ) : (
                <div className="text-center py-12">
                  <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                  <p className="text-xl text-gray-500 mb-4">
                    No sessions yet. Start a typing test to see your stats!
                  </p>
                  <button
                    onClick={() => setCurrentView("typing")}
                    className="px-6 py-3 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 transition-all shadow-md"
                  >
                    Start Your First Test
                  </button>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default TypingProductivityAnalyzer;
